export const ErrorCodes = {
  BAD_REQUEST : {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    CURRENCY_NOT_CONVERTIBLE: 'CURRENCY_NOT_CONVERTIBLE'
  },
  THIRD_PARTY_ERRORS : {
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE'
  }
}
